c   Graph      1
      data mapconfig(   1) /   1/
      data(iforest(i, -1,   1),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data(iforest(i, -2,   1),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data(iforest(i, -3,   1),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data(iforest(i, -4,   1),i=1,2) /  8, -2/          !  TMASS   TWIDTH  
      data(iforest(i, -5,   1),i=1,2) / -4, -3/          !  ZERO    ZERO    
      data mapconfig(   0) /   1/
