c   Graph      1
      data mapconfig(   1) /   1/
      data(iforest(i, -1,   1),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data(iforest(i, -2,   1),i=1,2) /  1,  5/          !  ZERO    ZERO    
      data(iforest(i, -3,   1),i=1,2) / -2, -1/          !  ZERO    ZERO    
      data(iforest(i, -4,   1),i=1,2) / -3,  6/          !  
c   Graph      2
      data mapconfig(   2) /   2/
      data(iforest(i, -1,   2),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data(iforest(i, -2,   2),i=1,2) /  6, -1/          !  ZERO    ZERO    
      data(iforest(i, -3,   2),i=1,2) /  1,  5/          !  ZERO    ZERO    
      data(iforest(i, -4,   2),i=1,2) / -3, -2/          !  
c   Graph      3
      data mapconfig(   3) /   3/
      data(iforest(i, -1,   3),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data(iforest(i, -2,   3),i=1,2) /  1,  6/          !  ZERO    ZERO    
      data(iforest(i, -3,   3),i=1,2) / -2, -1/          !  ZERO    ZERO    
      data(iforest(i, -4,   3),i=1,2) / -3,  5/          !  
c   Graph      4
      data mapconfig(   4) /   4/
      data(iforest(i, -1,   4),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data(iforest(i, -2,   4),i=1,2) /  6, -1/          !  ZERO    ZERO    
      data(iforest(i, -3,   4),i=1,2) /  1, -2/          !  ZERO    ZERO    
      data(iforest(i, -4,   4),i=1,2) / -3,  5/          !  
c   Graph      5
      data mapconfig(   5) /   5/
      data(iforest(i, -1,   5),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data(iforest(i, -2,   5),i=1,2) /  5, -1/          !  ZERO    ZERO    
      data(iforest(i, -3,   5),i=1,2) /  1,  6/          !  ZERO    ZERO    
      data(iforest(i, -4,   5),i=1,2) / -3, -2/          !  
c   Graph      6
      data mapconfig(   6) /   6/
      data(iforest(i, -1,   6),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data(iforest(i, -2,   6),i=1,2) /  5, -1/          !  ZERO    ZERO    
      data(iforest(i, -3,   6),i=1,2) /  1, -2/          !  ZERO    ZERO    
      data(iforest(i, -4,   6),i=1,2) / -3,  6/          !  
c   Graph      7
      data mapconfig(   7) /   7/
      data(iforest(i, -1,   7),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data(iforest(i, -2,   7),i=1,2) /  6, -1/          !  ZERO    ZERO    
      data(iforest(i, -3,   7),i=1,2) /  5, -2/          !  ZERO    ZERO    
c   Graph      8
      data mapconfig(   8) /   8/
      data(iforest(i, -1,   8),i=1,2) /  4,  3/          !  ZMASS   ZWIDTH  
      data(iforest(i, -2,   8),i=1,2) /  5, -1/          !  ZERO    ZERO    
      data(iforest(i, -3,   8),i=1,2) /  6, -2/          !  ZERO    ZERO    
      data mapconfig(   0) /   8/
