c   Graph      1
      data mapconfig(   1) /   1/
      data(iforest(i, -1,   1),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data(iforest(i, -2,   1),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data(iforest(i, -3,   1),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data(iforest(i, -4,   1),i=1,2) /  8, -2/          !  TMASS   TWIDTH  
      data(iforest(i, -5,   1),i=1,2) /  1, -4/          !  TMASS   TWIDTH  
      data(iforest(i, -6,   1),i=1,2) / -5, -3/          !  
c   Graph      2
      data mapconfig(   2) /   2/
      data(iforest(i, -1,   2),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data(iforest(i, -2,   2),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data(iforest(i, -3,   2),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data(iforest(i, -4,   2),i=1,2) /  8, -2/          !  TMASS   TWIDTH  
      data(iforest(i, -5,   2),i=1,2) /  1, -3/          !  TMASS   TWIDTH  
      data(iforest(i, -6,   2),i=1,2) / -5, -4/          !  
c   Graph      3
      data mapconfig(   3) /   3/
      data(iforest(i, -1,   3),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data(iforest(i, -2,   3),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data(iforest(i, -3,   3),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data(iforest(i, -4,   3),i=1,2) /  8, -2/          !  TMASS   TWIDTH  
      data(iforest(i, -5,   3),i=1,2) / -4, -3/          !  ZERO    ZERO    
      data mapconfig(   0) /   3/
